<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AssemblyName>AutoGreet</AssemblyName>
    <RootNamespace>AutoGreet</RootNamespace>
    <Version>1.0.21.0</Version>
    <Description>Venue host assistant for Final Fantasy XIV housing venues.</Description>
    <IsPackable>false</IsPackable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\default-doorbell.mp3" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    <EmbeddedResource Include="Resources\default-doorbell.mp3" />
  </ItemGroup>
</Project>
